package pe.ferresur.service;
import com.fasterxml.jackson.core.type.TypeReference; import com.fasterxml.jackson.databind.ObjectMapper; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import pe.ferresur.model.*; import pe.ferresur.repository.*; import java.math.BigDecimal; import java.time.LocalDate; import java.util.*;
@Service public class VentaService{
 private final VentaRepository ventaRepo; private final ProductoRepository productoRepo; private final UsuarioRepository usuarioRepo; private final ClienteRepository clienteRepo; private final ObjectMapper mapper;
 public VentaService(VentaRepository v,ProductoRepository p,UsuarioRepository u,ClienteRepository c,ObjectMapper m){ventaRepo=v;productoRepo=p;usuarioRepo=u;clienteRepo=c;mapper=m;}
 @Transactional public Venta registrar(String username,String itemsJson,Long clienteId,String tipoPagoStr,BigDecimal montoRecibido,LocalDate vencimiento)throws Exception{
  List<Map<String,Object>> items=mapper.readValue(itemsJson,new TypeReference<>(){}); if(items==null||items.isEmpty())throw new IllegalArgumentException("Debe agregar al menos un producto.");
  Usuario user=usuarioRepo.findByUsernameIgnoreCase(username).orElseThrow(); Venta venta=new Venta(); venta.setNumero(generarNumero()); venta.setVendedor(user);
  Venta.TipoPago tipo; try{tipo=Venta.TipoPago.valueOf(tipoPagoStr);}catch(Exception e){tipo=Venta.TipoPago.EFECTIVO;} venta.setTipoPago(tipo);
  if(clienteId!=null) venta.setCliente(clienteRepo.findById(clienteId).orElseThrow(()->new IllegalArgumentException("Cliente no encontrado.")));
  Map<Long,Integer> cantidades=new LinkedHashMap<>(); for(Map<String,Object> item:items){long id=Long.parseLong(item.get("id").toString());int qty=Integer.parseInt(item.get("cantidad").toString());if(qty<=0)throw new IllegalArgumentException("La cantidad debe ser mayor a cero.");cantidades.merge(id,qty,Integer::sum);}
  BigDecimal total=BigDecimal.ZERO; for(var e:cantidades.entrySet()){Producto p=productoRepo.findById(e.getKey()).orElseThrow();int qty=e.getValue();if(!p.isActivo())throw new IllegalArgumentException("Producto no disponible: "+p.getNombre());if(p.getStock()<qty)throw new IllegalArgumentException("Stock insuficiente para "+p.getNombre());BigDecimal subtotal=p.getPrecio().multiply(BigDecimal.valueOf(qty));DetalleVenta d=new DetalleVenta();d.setProducto(p);d.setCantidad(qty);d.setPrecioUnitario(p.getPrecio());d.setCostoUnitario(p.getCosto()==null?BigDecimal.ZERO:p.getCosto());d.setSubtotal(subtotal);venta.addDetalle(d);p.setStock(p.getStock()-qty);productoRepo.save(p);total=total.add(subtotal);}
  BigDecimal recibido=montoRecibido==null?BigDecimal.ZERO:montoRecibido.max(BigDecimal.ZERO); if(tipo==Venta.TipoPago.EFECTIVO){if(recibido.compareTo(total)<0)throw new IllegalArgumentException("El monto recibido es menor al total.");venta.setMontoRecibido(recibido);venta.setVuelto(recibido.subtract(total));venta.setSaldoPendiente(BigDecimal.ZERO);}else if(tipo==Venta.TipoPago.CREDITO){if(venta.getCliente()==null)throw new IllegalArgumentException("Una venta a crédito requiere cliente.");if(vencimiento==null)throw new IllegalArgumentException("Indique la fecha de vencimiento del crédito.");venta.setMontoRecibido(BigDecimal.ZERO);venta.setVuelto(BigDecimal.ZERO);venta.setSaldoPendiente(total);venta.setFechaVencimientoCredito(vencimiento);}else{venta.setMontoRecibido(total);venta.setVuelto(BigDecimal.ZERO);venta.setSaldoPendiente(BigDecimal.ZERO);}
  venta.setTotal(total); return ventaRepo.save(venta);
 }
 @Transactional public void anular(Long id){Venta v=ventaRepo.findById(id).orElseThrow();if(v.getEstado()==Venta.EstadoVenta.ANULADA)return;for(DetalleVenta d:v.getDetalles()){Producto p=d.getProducto();p.setStock(p.getStock()+d.getCantidad());productoRepo.save(p);}v.setEstado(Venta.EstadoVenta.ANULADA);ventaRepo.save(v);}
 private synchronized String generarNumero(){long n=ventaRepo.findTopByOrderByIdDesc().map(v->v.getId()+1).orElse(1L);String s=String.format("%04d",n);while(ventaRepo.findByNumero(s).isPresent()){n++;s=String.format("%04d",n);}return s;}
}
