package pe.ferresur.controller;
import org.springframework.security.core.Authentication; import org.springframework.stereotype.Controller; import org.springframework.ui.Model; import org.springframework.web.bind.annotation.*; import pe.ferresur.model.*; import pe.ferresur.repository.*; import java.math.*; import java.time.*;
@Controller @RequestMapping("/caja") public class CajaController{
 private final CajaRepository cajas; private final GastoRepository gastos; private final VentaRepository ventas; private final ProductoRepository productos; private final UsuarioRepository usuarios;
 public CajaController(CajaRepository c,GastoRepository g,VentaRepository v,ProductoRepository p,UsuarioRepository u){cajas=c;gastos=g;ventas=v;productos=p;usuarios=u;}
 @GetMapping public String index(Model m){LocalDate hoy=LocalDate.now();var caja=cajas.findByFechaAndEstado(hoy,Caja.Estado.ABIERTA).orElse(null);LocalDateTime d=hoy.atStartOfDay(),h=hoy.plusDays(1).atStartOfDay();BigDecimal efectivo=ventas.findByFechaBetweenOrderByFechaAsc(d,h.minusNanos(1)).stream().filter(v->v.getEstado()==Venta.EstadoVenta.COMPLETADA&&v.getTipoPago()==Venta.TipoPago.EFECTIVO).map(Venta::getTotal).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal gast=gastos.sumBetween(d,h.minusNanos(1));BigDecimal esperado=caja==null?BigDecimal.ZERO:caja.getMontoInicial().add(efectivo).subtract(gast==null?BigDecimal.ZERO:gast);m.addAttribute("caja",caja);m.addAttribute("efectivo",efectivo);m.addAttribute("gastosTotal",gast==null?BigDecimal.ZERO:gast);m.addAttribute("esperado",esperado);m.addAttribute("gastos",gastos.findByFechaBetweenOrderByFechaDesc(d,h.minusNanos(1)));m.addAttribute("productos",productos.findByActivoTrueOrderByNombreAsc());m.addAttribute("tiposGasto",Gasto.Tipo.values());m.addAttribute("stockBajoCount",productos.countStockBajo());return "caja/index";}
 @PostMapping("/abrir") public String abrir(Authentication auth,@RequestParam BigDecimal montoInicial,@RequestParam(required=false) String observaciones){LocalDate hoy=LocalDate.now();if(cajas.findByFechaAndEstado(hoy,Caja.Estado.ABIERTA).isEmpty()){Caja c=new Caja();c.setFecha(hoy);c.setMontoInicial(montoInicial.max(BigDecimal.ZERO));c.setAbiertoPor(usuarios.findByUsernameIgnoreCase(auth.getName()).orElse(null));c.setObservaciones(observaciones);cajas.save(c);}return "redirect:/caja";}
 @PostMapping("/gasto") public String gasto(Authentication auth,@RequestParam String tipo,@RequestParam String descripcion,@RequestParam BigDecimal monto,@RequestParam(required=false) Long productoId,@RequestParam(required=false) Integer cantidad){Gasto g=new Gasto();g.setTipo(Gasto.Tipo.valueOf(tipo));g.setDescripcion(descripcion);g.setMonto(monto);g.setUsuario(usuarios.findByUsernameIgnoreCase(auth.getName()).orElse(null));if(g.getTipo()==Gasto.Tipo.COMPRA_PRODUCTOS){if(productoId==null||cantidad==null||cantidad<1)return "redirect:/caja";Producto p=productos.findById(productoId).orElseThrow();p.setStock(p.getStock()+cantidad);if(monto.compareTo(BigDecimal.ZERO)>0)p.setCosto(monto.divide(BigDecimal.valueOf(cantidad),2,RoundingMode.HALF_UP));productos.save(p);g.setProducto(p);g.setCantidad(cantidad);}gastos.save(g);return "redirect:/caja";}
 @PostMapping("/cerrar") public String cerrar(Authentication auth,@RequestParam BigDecimal montoFinal,@RequestParam(required=false) String observaciones){Caja c=cajas.findByFechaAndEstado(LocalDate.now(),Caja.Estado.ABIERTA).orElseThrow();c.setMontoFinal(montoFinal);c.setCierre(LocalDateTime.now());c.setCerradoPor(usuarios.findByUsernameIgnoreCase(auth.getName()).orElse(null));c.setEstado(Caja.Estado.CERRADA);if(observaciones!=null&&!observaciones.isBlank())c.setObservaciones(observaciones);cajas.save(c);return "redirect:/caja";}
}
