package pe.ferresur.controller;
import org.springframework.security.core.Authentication; import org.springframework.stereotype.Controller; import org.springframework.ui.Model; import org.springframework.web.bind.annotation.*; import pe.ferresur.model.Venta; import pe.ferresur.repository.*; import pe.ferresur.service.VentaService; import java.math.*; import java.time.LocalDate;
@Controller @RequestMapping("/ventas") public class VentaController{
 private final VentaRepository ventas; private final ProductoRepository productos; private final VentaService service; private final ClienteRepository clientes;
 public VentaController(VentaRepository v,ProductoRepository p,VentaService s,ClienteRepository c){ventas=v;productos=p;service=s;clientes=c;}
 @GetMapping public String listar(Model model){var lista=ventas.findAll(org.springframework.data.domain.Sort.by(org.springframework.data.domain.Sort.Direction.DESC,"fecha"));BigDecimal total=lista.stream().filter(v->v.getEstado()==Venta.EstadoVenta.COMPLETADA).map(Venta::getTotal).reduce(BigDecimal.ZERO,BigDecimal::add);long comp=lista.stream().filter(v->v.getEstado()==Venta.EstadoVenta.COMPLETADA).count();long anul=lista.size()-comp;model.addAttribute("ventas",lista);model.addAttribute("totalVendido",total);model.addAttribute("completadas",comp);model.addAttribute("anuladas",anul);model.addAttribute("promedio",comp>0?total.divide(BigDecimal.valueOf(comp),2,RoundingMode.HALF_UP):BigDecimal.ZERO);model.addAttribute("stockBajoCount",productos.countStockBajo());return "ventas/index";}
 @GetMapping("/nueva") public String nueva(Model model){model.addAttribute("productos",productos.findByActivoTrueOrderByNombreAsc());model.addAttribute("clientes",clientes.findByActivoTrueOrderByNombreAsc());model.addAttribute("tiposPago",Venta.TipoPago.values());model.addAttribute("stockBajoCount",productos.countStockBajo());model.addAttribute("hoy",LocalDate.now());return "ventas/form";}
 @PostMapping("/guardar") public String guardar(Authentication auth,@RequestParam String itemsJson,@RequestParam(required=false) Long clienteId,@RequestParam String tipoPago,@RequestParam(required=false) BigDecimal montoRecibido,@RequestParam(required=false) LocalDate vencimiento,Model model){try{Venta v=service.registrar(auth.getName(),itemsJson,clienteId,tipoPago,montoRecibido,vencimiento);return "redirect:/ventas/"+v.getId()+"?ok=true";}catch(Exception e){model.addAttribute("error",e.getMessage());model.addAttribute("productos",productos.findByActivoTrueOrderByNombreAsc());model.addAttribute("clientes",clientes.findByActivoTrueOrderByNombreAsc());model.addAttribute("tiposPago",Venta.TipoPago.values());model.addAttribute("stockBajoCount",productos.countStockBajo());model.addAttribute("hoy",LocalDate.now());return "ventas/form";}}
 @GetMapping("/{id}") public String detalle(@PathVariable Long id,Model model){model.addAttribute("venta",ventas.findById(id).orElseThrow());return "ventas/detalle";}
 @GetMapping("/{id}/boleta") public String boleta(@PathVariable Long id,Model model){model.addAttribute("venta",ventas.findById(id).orElseThrow());return "ventas/boleta";}
 @PostMapping("/{id}/anular") public String anular(@PathVariable Long id){service.anular(id);return "redirect:/ventas";}
}
